# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

## Environment Properties

minecraft_version=1.21.4
minecraft_version_range=[1.21.4,)
neo_version=21.4.38-beta
neo_version_range=[21.4,)
loader_version_range=[4,)

parchment_minecraft_version=1.21.4
parchment_mappings_version=2024.12.07

mixin_version=0.15.0+mixin.0.8.7
mixinextras_version=0.4.0

## Mod Properties

mod_id=clean_tooltips
mod_name=Clean Tooltips
mod_license=All Rights Reserved
mod_version=1.0
mod_group_id=net.mandalacreations.clean_tooltips
mod_authors=stal111
mod_description=